### ISSUE TITLE
Accept (prime, exponent) arguments to GF constructor

### ISSUE THREAD

**Issue by kstauffer** [mhostetter/galois#117] opened 2021-06-08 19:36 UTC
`p = 2**61-1` is prime. galois.GF(p*p) takes ~3 hours to return. The factory already accepts a polynomial argument, so it would be really nice if I could say `galois.GF(p, [1, 0, 1])` and get on with using the quadratic extension (yes, `x**2 + 1` is irreducible over GF(p)).

**Comment by kstauffer** [comment] 2021-06-08 20:55
Awesome! Thanks for the quick & detailed response! Looking forward to beta testing!

**Comment by mhostetter** [comment] 2021-06-11 17:47
@kstauffer I just merged PR #123 that makes prime factoring of perfect powers much more efficient, I previously didn't have this algorithm which caused the 3 hour factoring of `p**2` in your case. :disappointed:

I can confirm on my machine that constructing your field is quite fast. The prime factoring takes negligible time now.

```python
In [1]: import galois                                                                                                  

In [2]: p = 2**61 - 1; p                                                                                                  
Out[2]: 2305843009213693951

In [3]: galois.prime_factors(p**2)                                                                                     
Out[3]: ([2305843009213693951], [2])

In [4]: %timeit galois.prime_factors(p**2)                                                                             
318 µs ± 3.31 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

Creating the field from scratch takes 7 seconds.

```python
In [1]: import galois                                                                                                  

In [2]: p = 2**61 - 1; p                                                                                               
Out[2]: 2305843009213693951

In [3]: %time GF = galois.GF(p**2, irreducible_poly=galois.Poly([1,0,1], field=galois.GF(p)))                          
CPU times: user 6.88 s, sys: 2.57 ms, total: 6.89 s
Wall time: 6.89 s
```

And caching the primitive element `x + 6` is even faster.

```python
In [1]: import galois                                                                                                  

In [2]: p = 2**61 - 1; p                                                                                               
Out[2]: 2305843009213693951

In [3]: irreducible_poly = galois.Poly([1,0,1], field=galois.GF(p)); irreducible_poly                                  
Out[3]: Poly(x^2 + 1, GF(2305843009213693951))

In [4]: %time primitive_element = galois.primitive_element(irreducible_poly); primitive_element                        
CPU times: user 6.67 s, sys: 0 ns, total: 6.67 s
Wall time: 6.67 s
Out[4]: Poly(x + 6, GF(2305843009213693951))

In [5]: %time GF = galois.GF(p**2, irreducible_poly=irreducible_poly, primitive_element=primitive_element)             
CPU times: user 1.25 s, sys: 0 ns, total: 1.25 s
Wall time: 1.26 s
```

And skipping the verification checks is even faster.

```python
In [5]: %time GF = galois.GF(p**2, irreducible_poly=irreducible_poly, primitive_element=primitive_element, verify_irred
   ...: ucible=False, verify_primitive=False)                                                                          
CPU times: user 2.92 ms, sys: 0 ns, total: 2.92 ms
Wall time: 2.93 ms

In [6]: print(GF)                                                                                                      
<class 'numpy.ndarray over GF(2305843009213693951^2)'>

In [7]: print(GF.properties)                                                                                           
GF(2305843009213693951^2):
  structure: Finite Field
  characteristic: 2305843009213693951
  degree: 2
  order: 5316911983139663487003542222693990401
  irreducible_poly: Poly(x^2 + 1, GF(2305843009213693951))
  is_primitive_poly: False
  primitive_element: GF(2305843009213693957, order=2305843009213693951^2)
```

I'm still open to changing the API from `galois.GF(order)` to `galois.GF(characteristic, degree)`, but seeing as the current API is now just as fast the modified API would be, I'm inclined to wait before changing the entire code base.

You can test this by installing the latest from master, `python3 -m pip install -U git+https://github.com/mhostetter/galois`.

**Comment by mhostetter** [comment] 2021-06-12 18:25
I do think it is still worth changing the class factory to allow tuples, lists, and np.ndarrays for `irreducible_poly` and `primitive_element`.

That way
```python
GF = galois.GF(p**2, irreducible_poly=galois.Poly([1,0,1], field=galois.GF(p)), primitive_element=galois.Poly([1,6], field=galois.GF(p)))
```
can be abbreviated to
```python
GF = galois.GF(p**2, irreducible_poly=[1,0,1], primitive_element=[1,6])
```

**Comment by mhostetter** [comment] 2021-06-13 13:58
#129 was merged onto master and allows tuples, lists, and ndarrays for `irreducible_poly` and `primitive_element`.

**Comment by mhostetter** [comment] 2021-06-24 14:06
I'm closing this for now due to inactivity. Please feel free to re-open with further thoughts or questions. Thanks again for the bug report!

**Closed by mhostetter** 2021-06-24 14:06 UTC
Labels: enhancement, performance
