### ISSUE TITLE
Issue `np.dot`

### ISSUE THREAD

**Issue by iyanmv** [mhostetter/galois#202] opened 2021-11-12 13:58 UTC
```python
import numpy as np
from galois import GF2

A = GF2([1, 0, 0, 1, 0])
B = GF2([
    [0, 1, 1, 1, 1],
    [1, 0, 1, 1, 1],
    [1, 1, 0, 1, 1],
    [0, 1, 1, 0, 1]
])

np.dot(B, A)  # it works
B @ A  # it works
B.dot(A)  # it fails!
```

**Comment by mhostetter** [comment] 2021-11-12 15:05
I actually didn't know that was valid syntax. But after looking it up, yes, you're right. That's a bug and should work as you expected.

I reproduced your example to see the stack trace and error.

```python
In [1]: import galois

In [2]: import numpy as np

In [3]: a = galois.GF2.Random(4); a
Out[3]: GF([1, 1, 1, 1], order=2)

In [4]: b = galois.GF2.Random((4,4)); b
Out[4]: 
GF([[0, 1, 0, 1],
    [0, 0, 0, 0],
    [0, 1, 1, 1],
    [0, 0, 0, 1]], order=2)

In [5]: np.dot(a, b)
Out[5]: GF([0, 0, 1, 1], order=2)

In [6]: a @ b
Out[6]: GF([0, 0, 1, 1], order=2)

In [7]: a.dot(b)
Out[7]: ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/lib/python3/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/usr/lib/python3/dist-packages/IPython/lib/pretty.py in pretty(self, obj)
    392                         if cls is not object \
    393                                 and callable(cls.__dict__.get('__repr__')):
--> 394                             return _repr_pprint(obj, self, cycle)
    395
    396             return _default_pprint(obj, self, cycle)

/usr/lib/python3/dist-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    682     """A pprint that just redirects to the normal repr function."""
    683     # Find newlines and replace them with p.break_()
--> 684     output = repr(obj)
    685     lines = output.splitlines()
    686     with p.group():

/mnt/c/Users/matth/repos/galois/galois/_fields/_array.py in __repr__(self)
   1203         with np.printoptions(formatter=formatter):
   1204             cls.__name__ = "GF"  # Rename the class so very large fields don't create large indenting
-> 1205             string = super().__repr__()
   1206         cls.__name__ = class_name
   1207

~/.local/lib/python3.8/site-packages/numpy/core/arrayprint.py in _array_repr_implementation(arr, max_line_width, precision, suppress_small, array2string)
   1411         lst = repr(arr.item())
   1412     elif arr.size > 0 or arr.shape == (0,):
-> 1413         lst = array2string(arr, max_line_width, precision, suppress_small,
   1414                            ', ', prefix, suffix=suffix)
   1415     else:  # show zero-length shape unless it is (0,)

~/.local/lib/python3.8/site-packages/numpy/core/arrayprint.py in array2string(a, max_line_width, precision, suppress_small, separator, prefix, style, formatter, threshold, edgeitems, sign, floatmode, suffix, 
legacy)
    690         return "[]"
    691
--> 692     return _array2string(a, options, separator, prefix)
    693
    694

~/.local/lib/python3.8/site-packages/numpy/core/arrayprint.py in wrapper(self, *args, **kwargs)
    466             repr_running.add(key)
    467             try:
--> 468                 return f(self, *args, **kwargs)
    469             finally:
    470                 repr_running.discard(key)

~/.local/lib/python3.8/site-packages/numpy/core/arrayprint.py in _array2string(a, options, separator, prefix)
    499     next_line_prefix += " "*len(prefix)
    500
--> 501     lst = _formatArray(a, format_function, options['linewidth'],
    502                        next_line_prefix, separator, options['edgeitems'],
    503                        summary_insert, options['legacy'])

~/.local/lib/python3.8/site-packages/numpy/core/arrayprint.py in _formatArray(a, format_function, line_width, next_line_prefix, separator, edge_items, summary_insert, legacy)
    843     try:
    844         # invoke the recursive part with an initial index and prefix
--> 845         return recurser(index=(),
    846                         hanging_indent=next_line_prefix,
    847                         curr_width=line_width)

~/.local/lib/python3.8/site-packages/numpy/core/arrayprint.py in recurser(index, hanging_indent, curr_width)
    799
    800             for i in range(trailing_items, 1, -1):
--> 801                 word = recurser(index + (-i,), next_hanging_indent, next_width)
    802                 s, line = _extendLine_pretty(
    803                     s, line, word, elem_width, hanging_indent, legacy)

~/.local/lib/python3.8/site-packages/numpy/core/arrayprint.py in recurser(index, hanging_indent, curr_width)
    753
    754         if axes_left == 0:
--> 755             return format_function(a[index])
    756
    757         # when recursing, add a space to align with the [ added, and reduce the

/mnt/c/Users/matth/repos/galois/galois/_fields/_array.py in __getitem__(self, key)
   1111             # Return scalar array elements as 0-dimensional Galois field arrays. This enables Galois field arithmetic
   1112             # on scalars, which would otherwise be implemented using standard integer arithmetic.
-> 1113             item = self.__class__(item, dtype=self.dtype)
   1114         return item
   1115

/mnt/c/Users/matth/repos/galois/galois/_fields/_array.py in __new__(cls, array, dtype, copy, order, ndmin)
    116         if cls is FieldArray:
    117             raise NotImplementedError("FieldArray is an abstract base class that cannot be directly instantiated. Instead, create a FieldArray subclass for GF(p^m) arithmetic using `GF = galois.GF(p**m)` and instantiate an array using `x = GF(array_like)`.")
--> 118         return cls._array(array, dtype=dtype, copy=copy, order=order, ndmin=ndmin)
    119
    120     def __init__(self, array, dtype=None, copy=True, order="K", ndmin=0):

/mnt/c/Users/matth/repos/galois/galois/_fields/_array.py in _array(cls, array_like, dtype, copy, order, ndmin)
    171     def _array(cls, array_like, dtype=None, copy=True, order="K", ndmin=0):
    172         dtype = cls._get_dtype(dtype)
--> 173         array_like = cls._check_array_like_object(array_like)
    174         array = np.array(array_like, dtype=dtype, copy=copy, order=order, ndmin=ndmin)
    175         return array.view(cls)

/mnt/c/Users/matth/repos/galois/galois/_fields/_array.py in _check_array_like_object(cls, array_like)
    187         elif isinstance(array_like, (int, np.integer)):
    188             # Just check that the single int is in range
--> 189             cls._check_array_values(array_like)
    190         elif isinstance(array_like, (list, tuple)):
    191             # Recursively check the items in the iterable to ensure they're of the correct type

/mnt/c/Users/matth/repos/galois/galois/_fields/_array.py in _check_array_values(cls, array)
    257             idxs = np.logical_or(array < 0, array >= cls.order)
    258             values = array if array.ndim == 0 else array[idxs]
--> 259             raise ValueError(f"{cls.name} arrays must have elements in `0 <= x < {cls.order}`, not {values}.")
    260
    261     @classmethod

ValueError: GF(2) arrays must have elements in `0 <= x < 2`, not 2.
```

The issue is that the normal `np.dot` is being called on the two arrays and the result has values greater than 2. I can open a PR to fix this.

**Comment by mhostetter** [comment] 2021-11-12 15:43
@iyanmv I just opened #203 to resolve this. It appears `ndarray.dot()` is the only linear algebra method like that. That is, there is no `ndarray.vdot()` or `ndarray.inner()` method.

I have the new output of your example in the description of the PR. Thoughts? If satisfactory, I'll merge and close this.

**Comment by iyanmv** [comment] 2021-11-12 17:49
Ups, I missed this comment. Yes, look good to me.

**Comment by mhostetter** [comment] 2021-11-12 19:03
With #203 merged into `master`, I'm closing.

**Closed by mhostetter** 2021-11-12 19:03 UTC
Labels: bug, reproducible
